name: termdo

services:
  web:
    build:
      context: .
      args:
        PUBLIC_APP_ENV: ${PUBLIC_APP_ENV}
        PUBLIC_APP_VER: ${PUBLIC_APP_VER}
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:80"

networks:
  default:
    name: termdo-net
